import "./globals.css";
import Sidebar from "@/components/sidebar/page";
import Topbar from "@/components/topbar/page";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased font-system">
        {/* Shell with Sidebar (left) + Topbar (top) */}
        <div className="min-h-screen bg-gray-50 text-gray-900 flex">
          <Sidebar />
          <main className="flex-1 min-h-screen">
            <Topbar />
            <div className="p-6">{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
